version: '3.8'

services:
  btc-redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      -   spring-security-angular


networks:
  spring-security-angular: